-- Update kategori detail (merek) & satuan hasil pencocokan nama

update items set kategori = 'ADVANSIA' where kode = 'ABD-40GR';
update items set kategori = 'ADVANSIA' where kode = 'ABJ 60WP-100GR';
update items set kategori = 'ADVANSIA' where kode = 'ABJ 60WP-50GR';
update items set kategori = 'DGW' where kode = 'ABO-200ML';
update items set kategori = 'BAYER' where kode = 'ABT-1LTR';
update items set kategori = 'BAYER' where kode = 'ABT-500ML';
update items set kategori = 'AGRICON' where kode = 'ABU-100ML';
update items set kategori = 'AGRICON' where kode = 'ABU-250ML';
update items set kategori = 'AGRICON' where kode = 'ABU-500ML';
update items set kategori = 'SGI' where kode = 'ACE-100GR';
update items set kategori = 'BASF' where kode = 'ACR-10GR';
update items set kategori = 'BASF' where kode = 'ACR-40GR';
update items set kategori = 'ADVANSIA' where kode = 'ADL-100ML';
update items set kategori = 'NUFARM' where kode = 'AGE-250ML';
update items set kategori = 'SARANA PERTANIAN' where kode = 'AGK-250ML';
update items set kategori = 'SYNGENTA' where kode = 'AGMC-250ML';
update items set kategori = 'BAYER' where kode = 'AGR-1LTR';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'AGT-75S';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'AGT-SP';
update items set kategori = 'ADVANSIA' where kode = 'AGU-100ML';
update items set kategori = 'ADVANSIA' where kode = 'AJN-25GR';
update items set kategori = 'SANTANI' where kode = 'AJO-250ML';
update items set kategori = 'AGRICON' where kode = 'ALA-200ML';
update items set kategori = 'SYNGENTA' where kode = 'ALI-250ML';
update items set kategori = 'SARANA PERTANIAN' where kode = 'ALJ-SINGLE';
update items set kategori = 'SYNGENTA' where kode = 'ALK-100ML';
update items set kategori = 'SYNGENTA' where kode = 'ALK-50ML';
update items set kategori = 'FMC' where kode = 'ALL-5GR';
update items set kategori = 'ADVANSIA' where kode = 'AM-100ML';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'AMA-360S';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'AMA-SP';
update items set kategori = 'SOLO LOGO' where kode = 'AMB-1LTR';
update items set kategori = 'PT ADIL MAKMUR' where kode = 'AMC-1LTR';
update items set kategori = 'PT ADIL MAKMUR' where kode = 'AMI-400ML';
update items set kategori = 'ADVANSIA' where kode = 'AMK-250ML';
update items set kategori = 'ADVANSIA' where kode = 'AMR-100ML';
update items set kategori = 'SYNGENTA' where kode = 'AMS-100ML';
update items set kategori = 'PT ADIL MAKMUR' where kode = 'AMS-1L';
update items set kategori = 'SYNGENTA' where kode = 'AMS-250ML';
update items set kategori = 'SYNGENTA' where kode = 'AMS-50ML';
update items set kategori = 'PT ADIL MAKMUR' where kode = 'AMSN-250ML';
update items set kategori = 'BAYER' where kode = 'ANT-1KG';
update items set kategori = 'BAYER' where kode = 'ANT-250GR';
update items set kategori = 'BAYER' where kode = 'ANT-500GR';
update items set kategori = 'ADVANSIA' where kode = 'APC-250GR';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'AQUI-SP';
update items set kategori = 'PUPUK' where kode = 'ASP-50KG';
update items set kategori = 'DGW' where kode = 'AST-100ML';
update items set kategori = 'DGW' where kode = 'AST-250ML';
update items set kategori = 'SGI' where kode = 'AST-400GR';
update items set kategori = 'DGW' where kode = 'AST-500ML';
update items set kategori = 'SGI' where kode = 'AST60-100GR';
update items set kategori = 'ADVANSIA' where kode = 'AT-100ML';
update items set kategori = 'ADVANSIA' where kode = 'AT-200GR';
update items set kategori = 'ADVANSIA' where kode = 'AT-250ML';
update items set kategori = 'NUFARM' where kode = 'ATM-500ML';
update items set kategori = 'PUPUK CAIR' where kode = 'ATO-100ML';
update items set kategori = 'PUPUK CAIR' where kode = 'ATO-500ML';
update items set kategori = 'NUFARM' where kode = 'ATR-500ML';
update items set kategori = 'ADVANSIA' where kode = 'ATZ-250ML';
update items set kategori = 'BIBIT JAGUNG MANIS PANAH MERAH' where kode = 'B-MB';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'BAN-1KG';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'BAN-SP';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'BAR-800S';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'BAR-SP';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'BARA-SP';
update items set kategori = 'PETROKIMIA' where kode = 'BAS-100ML';
update items set kategori = 'BASF' where kode = 'BAS-1KG';
update items set kategori = 'PETROKIMIA' where kode = 'BAS-500ML';
update items set kategori = 'BASF' where kode = 'BAS-50KG';
update items set kategori = 'PETROKIMIA' where kode = 'BASM-1LTR';
update items set kategori = 'PETROKIMIA' where kode = 'BASM-5LTR';
update items set kategori = 'BASF' where kode = 'BASS-50KG';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'BAT-800S';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'BAT-SP';
update items set kategori = 'BELL' where kode = 'BEL-4KG';
update items set kategori = 'DGW' where kode = 'BEN 250GR';
update items set kategori = 'DGW' where kode = 'BES-100GR';
update items set kategori = 'DGW' where kode = 'BES-50GR';
update items set kategori = 'AGRICON' where kode = 'BFY-100ML';
update items set kategori = 'PETROKIMIA' where kode = 'BGS-20LTR';
update items set kategori = 'AGRICON' where kode = 'BLA-100ML';
update items set kategori = 'DGW' where kode = 'BLS-100ML';
update items set kategori = 'DGW' where kode = 'BLS-200ML';
update items set kategori = 'DGW' where kode = 'BLT-500ML';
update items set kategori = 'DGW' where kode = 'BLT-50ML';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'BLZ-10GR';
update items set kategori = 'SYNGENTA' where kode = 'BNM-500GR';
update items set kategori = 'BIBIT JAGUNG MANIS PANAH MERAH' where kode = 'BOB-1800S';
update items set kategori = 'NUFARM' where kode = 'BOO-250ML';
update items set kategori = 'NUFARM' where kode = 'BOO-80ML';
update items set kategori = 'PUPUK CAIR' where kode = 'BP-1LT';
update items set kategori = 'SGI' where kode = 'BRA-1KG';
update items set kategori = 'SGI' where kode = 'BRA-500GR';
update items set kategori = 'MULTI SARANA INDOTANI' where kode = 'BRD-100GR';
update items set kategori = 'DGW' where kode = 'BRN-1LTR';
update items set kategori = 'DGW' where kode = 'BRN-4LTR';
update items set kategori = 'AIC/JAI' where kode = 'BRX-1LTR';
update items set kategori = 'AIC/JAI' where kode = 'BRX-20LTR';
update items set kategori = 'AIC/JAI' where kode = 'BRX-4LTR';
update items set kategori = null where kode = 'BYCRB 100ML';
update items set kategori = 'CIPTA MAKMUR PERTIWI (CMP)' where kode = 'C15-50KG';
update items set kategori = 'SGI' where kode = 'C45-1KG';
update items set kategori = 'CIPTA MAKMUR PERTIWI (CMP)' where kode = 'C7B-1LTR';
update items set kategori = 'MEROKE' where kode = 'CAL-1KG';
update items set kategori = 'MEROKE' where kode = 'CAL-25KG';
update items set kategori = 'BASF' where kode = 'CAN-1KG';
update items set kategori = 'BASF' where kode = 'CAN-50KG';
update items set kategori = 'BASF' where kode = 'CAN-5KG';
update items set kategori = 'DGW' where kode = 'CAP-500ML';
update items set kategori = 'SGI' where kode = 'CBF-2KG';
update items set kategori = 'PETROKIMIA' where kode = 'CEB-100ML';
update items set kategori = 'PETROKIMIA' where kode = 'CEB-200ML';
update items set kategori = 'PUPUK' where kode = 'CEN-50KG';
update items set kategori = 'NUFARM' where kode = 'CH-250ML';
update items set kategori = 'NUFARM' where kode = 'CH-500ML';
update items set kategori = 'NUFARM' where kode = 'CHIX-100ML';
update items set kategori = 'DGW' where kode = 'CHL-400ML';
update items set kategori = 'SGI' where kode = 'CHLCYN-100ML';
update items set kategori = 'DGW' where kode = 'CHMR-100ML';
update items set kategori = 'CIPTA MAKMUR PERTIWI (CMP)' where kode = 'CIP10%-50KG';
update items set kategori = 'CIPTA MAKMUR PERTIWI (CMP)' where kode = 'CIP20%-50KG';
update items set kategori = 'MITRA MERDEKA TANI' where kode = 'CLH-1KG';
update items set kategori = 'DGW' where kode = 'CLM-100ML';
update items set kategori = 'DGW' where kode = 'CLM-200ML';
update items set kategori = 'DGW' where kode = 'CLM-900ML';
update items set kategori = 'AIC/JAI' where kode = 'CMX-1LTR';
update items set kategori = 'AIC/JAI' where kode = 'CMX-20LTR';
update items set kategori = 'AIC/JAI' where kode = 'CMX-4LTR';
update items set kategori = 'SAPROTAN UTAMA' where kode = 'CNG 1KG';
update items set kategori = 'MULTI SARANA INDOTANI' where kode = 'COP-100GR';
update items set kategori = 'MULTI SARANA INDOTANI' where kode = 'COP-400GR';
update items set kategori = 'SANTANI' where kode = 'CORN-500ML';
update items set kategori = 'PLASINDO' where kode = 'COVIT-PS';
update items set kategori = 'PUPUK' where kode = 'CPN-1KG';
update items set kategori = 'MEROKE' where kode = 'CPN-25KG';
update items set kategori = 'SAPROTAN UTAMA' where kode = 'CPN-2KG';
update items set kategori = 'SYNGENTA' where kode = 'CRU-12,5ML';
update items set kategori = 'SANTANI' where kode = 'CS-1KG';
update items set kategori = 'CIPTA MAKMUR PERTIWI (CMP)' where kode = 'CSP36-50KG';
update items set kategori = 'SANTANI' where kode = 'CUAN-20LT';
update items set kategori = 'SYNGENTA' where kode = 'CUR-100ML';
update items set kategori = 'SYNGENTA' where kode = 'CUR-250ML';
update items set kategori = 'SYNGENTA' where kode = 'CUR-500ML';
update items set kategori = 'DGW' where kode = 'CZE-1KG';
update items set kategori = 'DGW' where kode = 'DAI-250GR';
update items set kategori = 'DGW' where kode = 'DAN-100GR';
update items set kategori = 'DGW' where kode = 'DAN-250GR';
update items set kategori = 'DGW' where kode = 'DAPS-50KG';
update items set kategori = 'PT PPI' where kode = 'DBS-100ML';
update items set kategori = 'PT PPI' where kode = 'DBS-400ML';
update items set kategori = 'BUNGA TANI' where kode = 'DDT-250GR';
update items set kategori = 'BUNGA TANI' where kode = 'DDT-500GR';
update items set kategori = 'BAYER' where kode = 'DEC-100ML';
update items set kategori = 'BAYER' where kode = 'DEC-250ML';
update items set kategori = 'BAYER' where kode = 'DEC-50ML';
update items set kategori = 'SGI' where kode = 'DEL-100ML';
update items set kategori = 'SGI' where kode = 'DEL-1LTR';
update items set kategori = 'SGI' where kode = 'DEL-200ML';
update items set kategori = 'DGW' where kode = 'DEM-100ML';
update items set kategori = 'DGW' where kode = 'DEM-200ML';
update items set kategori = 'DGW' where kode = 'DEM-50ML';
update items set kategori = 'DGW' where kode = 'DEN-200ML';
update items set kategori = 'DGW' where kode = 'DEN-500ML';
update items set kategori = 'DGW' where kode = 'DGW16-50KG';
update items set kategori = 'SGI' where kode = 'DGY-100GR';
update items set kategori = 'FUNGISIDA' where kode = 'DIT-1KG';
update items set kategori = 'FUNGISIDA' where kode = 'DIT-200GR';
update items set kategori = 'FUNGISIDA' where kode = 'DIT-500GR';
update items set kategori = 'PUPUK' where kode = 'DLASM-50KG';
update items set kategori = 'PT PPI' where kode = 'DMS-100ML';
update items set kategori = 'PT PPI' where kode = 'DMS-500ML';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'DWG-10GR';
update items set kategori = 'BASF' where kode = 'E16-1KG';
update items set kategori = 'BASF' where kode = 'E16-50KG';
update items set kategori = 'BASF' where kode = 'E17 - 1KG';
update items set kategori = 'BASF' where kode = 'E17-50KG';
update items set kategori = 'EM4' where kode = 'EM4-01';
update items set kategori = 'EM4' where kode = 'EM4-02';
update items set kategori = 'EM4' where kode = 'EM4-03';
update items set kategori = 'EM4' where kode = 'EM4-04';
update items set kategori = 'SANTANI' where kode = 'ENT-25KG';
update items set kategori = 'NUFARM' where kode = 'ENV-100GR';
update items set kategori = 'BIBIT JAGUNG MANIS PERTIWI' where kode = 'EXO-1750S';
update items set kategori = 'SGI' where kode = 'EXO-1LTR';
update items set kategori = 'SGI' where kode = 'EXO-250ML';
update items set kategori = 'SGI' where kode = 'EXON-500ML';
update items set kategori = 'DGW' where kode = 'EXP-250ML';
update items set kategori = 'DGW' where kode = 'EXP-80ML';
update items set kategori = 'SAPROTAN UTAMA' where kode = 'FER-50KG';
update items set kategori = 'SYNGENTA' where kode = 'FIL-250ML';
update items set kategori = 'SYNGENTA' where kode = 'FIL-50ML';
update items set kategori = 'MEROKE' where kode = 'FIT-2.5GR';
update items set kategori = 'MEROKE' where kode = 'FLG-25KG';
update items set kategori = 'SGI' where kode = 'FRM-1LTR';
update items set kategori = 'SGI' where kode = 'FRM-4LTR';
update items set kategori = 'SAPROTAN UTAMA' where kode = 'FRTLHJ-50KG';
update items set kategori = 'MEROKE' where kode = 'FSF-50KG';
update items set kategori = 'PUPUK' where kode = 'FT-25KG';
update items set kategori = 'FMC' where kode = 'FUR-1KG';
update items set kategori = 'FMC' where kode = 'FUR-2KG';
update items set kategori = 'CORTEVA' where kode = 'GAL-500ML';
update items set kategori = 'PUPUK' where kode = 'GANB-100GR';
update items set kategori = 'PUPUK' where kode = 'GANB-500GR';
update items set kategori = 'PUPUK' where kode = 'GAND-100GR';
update items set kategori = 'PUPUK' where kode = 'GAND-500GR';
update items set kategori = 'CORTEVA' where kode = 'GAR-100ML';
update items set kategori = 'CORTEVA' where kode = 'GAR-1LTR';
update items set kategori = 'SARANA PERTANIAN' where kode = 'GEM-11LTR';
update items set kategori = 'PETROKIMIA' where kode = 'GEM-1LTR';
update items set kategori = 'SARANA PERTANIAN' where kode = 'GEM-3LTR';
update items set kategori = 'SARANA PERTANIAN' where kode = 'GEM-5LTR';
update items set kategori = 'NUFARM' where kode = 'GIB -1GR';
update items set kategori = 'NUFARM' where kode = 'GIBP-1GR';
update items set kategori = 'BIOTIS' where kode = 'GLF-1LTR';
update items set kategori = 'SGI' where kode = 'GLU-1L';
update items set kategori = 'SGI' where kode = 'GLU-20L';
update items set kategori = 'SGI' where kode = 'GLU-4L';
update items set kategori = 'SYNGENTA' where kode = 'GMX-1LTR';
update items set kategori = 'SYNGENTA' where kode = 'GMX-20LT';
update items set kategori = 'SYNGENTA' where kode = 'GMX-500ML';
update items set kategori = 'SYNGENTA' where kode = 'GMX-5LT';
update items set kategori = 'SGI' where kode = 'GN-250GR';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'GRD-500GR';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'GRD-SP';
update items set kategori = 'CBA' where kode = 'GRIP-4LTR';
update items set kategori = 'SGI' where kode = 'GRN-100GR';
update items set kategori = 'SGI' where kode = 'GRN-200GR';
update items set kategori = 'SGI' where kode = 'GRN-400GR';
update items set kategori = 'MULTI SARANA INDOTANI' where kode = 'GRT-100ML';
update items set kategori = 'MULTI SARANA INDOTANI' where kode = 'GRT-500ML';
update items set kategori = 'SGI' where kode = 'GRU-1LTR';
update items set kategori = 'SGI' where kode = 'GRU-20LTR';
update items set kategori = 'SGI' where kode = 'GRU-4LTR';
update items set kategori = 'PUPUK CAIR' where kode = 'GTL-1LTR';
update items set kategori = 'PUPUK CAIR' where kode = 'GTP-500L';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'GUS-RG';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'GUS-SP';
update items set kategori = 'JIMMY HANTU' where kode = 'HAN-EX 1LTR';
update items set kategori = 'JIMMY HANTU' where kode = 'HAN-EX250ML';
update items set kategori = 'JIMMY HANTU' where kode = 'HAN-EX500ML';
update items set kategori = 'JIMMY HANTU' where kode = 'HAN-RB1LTR';
update items set kategori = 'JIMMY HANTU' where kode = 'HAN-RB500ML';
update items set kategori = 'JIMMY HANTU' where kode = 'HAN-TAN1LTR';
update items set kategori = 'JIMMY HANTU' where kode = 'HAN-TAN250ML';
update items set kategori = 'JIMMY HANTU' where kode = 'HAN-TAN500ML';
update items set kategori = 'JIMMY HANTU' where kode = 'HANLAN-250ML';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'HIT-1100S';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'HIT-SP';
update items set kategori = 'SARANA PERTANIAN' where kode = 'HUN-38';
update items set kategori = 'SARANA PERTANIAN' where kode = 'HUN-39';
update items set kategori = 'SARANA PERTANIAN' where kode = 'HUN-40';
update items set kategori = 'SARANA PERTANIAN' where kode = 'HUN-41';
update items set kategori = 'SARANA PERTANIAN' where kode = 'HUN-42';
update items set kategori = 'SARANA PERTANIAN' where kode = 'HUN-43';
update items set kategori = 'SYNGENTA' where kode = 'ICP-100ML';
update items set kategori = 'PUPUK CAIR' where kode = 'IDV-1LTR';
update items set kategori = 'JIMMY HANTU' where kode = 'IRR-1LTR';
update items set kategori = null where kode = 'JDM13627';
update items set kategori = 'LAIN-LAIN' where kode = 'JH';
update items set kategori = 'SAPROTAN UTAMA' where kode = 'JON-1LTR';
update items set kategori = 'SAPROTAN UTAMA' where kode = 'JON-20LTR';
update items set kategori = 'SAPROTAN UTAMA' where kode = 'JON-4LTR';
update items set kategori = 'PUPUK' where kode = 'JRP-50KG';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'JW-SP';
update items set kategori = null where kode = 'KAIN-SRG';
update items set kategori = 'MEROKE' where kode = 'KAL-1KG';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'KAN-500GR';
update items set kategori = null where kode = 'KAOS';
update items set kategori = 'LAIN-LAIN' where kode = 'KAP-15KG';
update items set kategori = null where kode = 'KBP';
update items set kategori = null where kode = 'KBS';
update items set kategori = null where kode = 'KC';
update items set kategori = 'SAPROTAN UTAMA' where kode = 'KCL-5KG';
update items set kategori = null where kode = 'KE';
update items set kategori = 'LAIN-LAIN' where kode = 'KEN-KSG 20LTR';
update items set kategori = 'LAIN-LAIN' where kode = 'KEN-KSG 4LTR';
update items set kategori = 'SGI' where kode = 'KEO';
update items set kategori = 'BIBIT' where kode = 'KGK-1KG';
update items set kategori = 'PETROKIMIA' where kode = 'KIEM-50KG';
update items set kategori = null where kode = 'KK';
update items set kategori = 'BISI' where kode = 'KKB-1KG';
update items set kategori = null where kode = 'KLC';
update items set kategori = 'SYNGENTA' where kode = 'KLE-1KG';
update items set kategori = 'SYNGENTA' where kode = 'KLE-5KG';
update items set kategori = 'MITRA MERDEKA TANI' where kode = 'KLN-1LTR';
update items set kategori = 'MITRA MERDEKA TANI' where kode = 'KLN-250ML';
update items set kategori = 'MITRA MERDEKA TANI' where kode = 'KLN-500ML';
update items set kategori = 'DGW' where kode = 'KLS-200ML';
update items set kategori = 'NUFARM' where kode = 'KLU-1LTR';
update items set kategori = 'NUFARM' where kode = 'KLU-20LTR';
update items set kategori = 'NUFARM' where kode = 'KLU-4LTR';
update items set kategori = null where kode = 'KLW';
update items set kategori = 'PUPUK' where kode = 'KMAH-50KG';
update items set kategori = 'PUPUK' where kode = 'KMW-50KG';
update items set kategori = 'MEROKE' where kode = 'KNK-50KG';
update items set kategori = 'SAPROTAN UTAMA' where kode = 'KNO-1KG';
update items set kategori = 'SAPROTAN UTAMA' where kode = 'KNO-2KG';
update items set kategori = 'SGI' where kode = 'KON-100ML';
update items set kategori = 'SGI' where kode = 'KON-1LTR';
update items set kategori = 'SGI' where kode = 'KON-250ML';
update items set kategori = 'SGI' where kode = 'KON-4LTR';
update items set kategori = 'SGI' where kode = 'KON-500ML';
update items set kategori = 'SANTANI' where kode = 'KOT-250ML';
update items set kategori = 'SANTANI' where kode = 'KOT-500ML';
update items set kategori = 'MEROKE' where kode = 'KPB-25KG';
update items set kategori = 'PETROKIMIA' where kode = 'KPT-50KG';
update items set kategori = null where kode = 'KR';
update items set kategori = 'INSEKTISIDA' where kode = 'KRL-100ML';
update items set kategori = null where kode = 'KRX-1LT';
update items set kategori = null where kode = 'KRX-20LT';
update items set kategori = null where kode = 'KRX-4LT';
update items set kategori = null where kode = 'KS';
update items set kategori = null where kode = 'KS-PRBC';
update items set kategori = null where kode = 'KSGI';
update items set kategori = 'ZAT PENGATUR TUMBUH' where kode = 'KTR-1LTR';
update items set kategori = 'ZAT PENGATUR TUMBUH' where kode = 'KTRM-1L';
update items set kategori = 'ZAT PENGATUR TUMBUH' where kode = 'KTRM-500ML';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'KUM-250GR';
update items set kategori = 'BIBIT JAGUNG MANIS PANAH MERAH' where kode = 'KUM-SP';
update items set kategori = 'NUFARM' where kode = 'KUP-200ML';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'KUS-95S';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'KUS-SP';
update items set kategori = null where kode = 'KV';
update items set kategori = 'SAPROTAN UTAMA' where kode = 'KZM-80ML';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'LAB-SP';
update items set kategori = 'CBA' where kode = 'LAL-1LTR';
update items set kategori = 'CBA' where kode = 'LAL-4L';
update items set kategori = 'INSEKTISIDA' where kode = 'LBR-100GR';
update items set kategori = 'INSEKTISIDA' where kode = 'LBR-250GR';
update items set kategori = 'NUFARM' where kode = 'LDM-1LTR';
update items set kategori = 'DGW' where kode = 'LEI-250ML';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'LEZ-1100S';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'LEZ-SP';
update items set kategori = 'NUFARM' where kode = 'LGN-500ML';
update items set kategori = 'SGI' where kode = 'LIN-1LTR';
update items set kategori = 'BUNGA TANI' where kode = 'LIN-500GR';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'LIP-SP';
update items set kategori = 'INSEKTISIDA' where kode = 'LMR-100GR';
update items set kategori = 'INSEKTISIDA' where kode = 'LMR-15GR';
update items set kategori = 'INSEKTISIDA' where kode = 'LMR-500GR';
update items set kategori = 'BUNGA TANI' where kode = 'LOD-500GR';
update items set kategori = 'SGI' where kode = 'LOG-100ML';
update items set kategori = 'SGI' where kode = 'LOG-250ML';
update items set kategori = 'SGI' where kode = 'LOG-500ML';
update items set kategori = 'MEROKE' where kode = 'M16-1KG';
update items set kategori = 'MEROKE' where kode = 'M16-50KG';
update items set kategori = 'AIC/JAI' where kode = 'MAC-500GR';
update items set kategori = 'AIC/JAI' where kode = 'MAC-80GR';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'MAE-500GR';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'MAE-SP';
update items set kategori = 'SAPROTAN UTAMA' where kode = 'MAG-S-1KG';
update items set kategori = 'PUPUK' where kode = 'MAGRH-500GR';
update items set kategori = 'PUPUK' where kode = 'MAGRM-500GR';
update items set kategori = 'MEROKE' where kode = 'MAGS-1KG';
update items set kategori = 'MEROKE' where kode = 'MAGS-25KG';
update items set kategori = 'PUPUK' where kode = 'MAH13.6.27-50KG';
update items set kategori = 'PUPUK' where kode = 'MAH13.8.27-50KG';
update items set kategori = 'SGI' where kode = 'MAN-1LTR';
update items set kategori = 'SGI' where kode = 'MAN-20LTR';
update items set kategori = 'SGI' where kode = 'MAN-4LTR';
update items set kategori = 'FUNGISIDA' where kode = 'MAN-500GR';
update items set kategori = 'SGI' where kode = 'MAN-500ML';
update items set kategori = 'MEROKE' where kode = 'MAP-1KG';
update items set kategori = 'FMC' where kode = 'MAR-1KG';
update items set kategori = 'FMC' where kode = 'MAR-25GR';
update items set kategori = 'FMC' where kode = 'MAR-500GR';
update items set kategori = 'AGRICON' where kode = 'MAX-100GR';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'MAX-SP';
update items set kategori = 'BELL' where kode = 'MBL100-17KG';
update items set kategori = 'BELL' where kode = 'MBL120-17KG';
update items set kategori = 'BELL' where kode = 'MBL120-8KG';
update items set kategori = 'BELL' where kode = 'MBL160-17KG';
update items set kategori = 'BELL' where kode = 'MBL80-17KG';
update items set kategori = 'BELL' where kode = 'MBL80-8KG';
update items set kategori = 'CAHAYA BOLA' where kode = 'MCB120-18KG';
update items set kategori = 'CAHAYA BOLA' where kode = 'MCB120-8KG';
update items set kategori = 'MEROKE' where kode = 'MCPN -1KG';
update items set kategori = 'MITRA MERDEKA TANI' where kode = 'MDF-1LTR';
update items set kategori = 'MITRA MERDEKA TANI' where kode = 'MDF-250ML';
update items set kategori = 'MITRA MERDEKA TANI' where kode = 'MDF-500ML';
update items set kategori = 'BIOTIS' where kode = 'MEU-100ML';
update items set kategori = 'BIOTIS' where kode = 'MEU-250ML';
update items set kategori = 'MEROKE' where kode = 'MGRO-1KG';
update items set kategori = 'MEROKE' where kode = 'MGRO-50KG';
update items set kategori = 'NUFARM' where kode = 'MIC-1KG';
update items set kategori = 'PETROKIMIA' where kode = 'MIP-100GR';
update items set kategori = 'PETROKIMIA' where kode = 'MIP-500GR';
update items set kategori = 'MEROKE' where kode = 'MKP-M-1KG';
update items set kategori = 'SAPROTAN UTAMA' where kode = 'MKP-S-1KG';
update items set kategori = 'MEROKE' where kode = 'MOP-HA50KG';
update items set kategori = 'SGI' where kode = 'MOR-100ML';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'MOR-20GR';
update items set kategori = 'AGRICON' where kode = 'MOS-100ML';
update items set kategori = 'AGRICON' where kode = 'MOS-400ML';
update items set kategori = 'NUFARM' where kode = 'MOX-100ML';
update items set kategori = 'PANEN RAYA' where kode = 'MPRP-8KG';
update items set kategori = 'SOLO LOGO' where kode = 'MPT-5GR';
update items set kategori = 'PETROKIMIA' where kode = 'MRN-500GR';
update items set kategori = 'SYNGENTA' where kode = 'MRV-100ML';
update items set kategori = 'SYNGENTA' where kode = 'MRV-250ML';
update items set kategori = 'PETROKIMIA' where kode = 'MTB-1KG';
update items set kategori = 'SYNGENTA' where kode = 'MTD 25EC-50ML';
update items set kategori = 'SYNGENTA' where kode = 'MTD-250ML';
update items set kategori = 'SYNGENTA' where kode = 'MTD-80ML';
update items set kategori = 'DGW' where kode = 'MTH-100GR';
update items set kategori = 'SARANA PERTANIAN' where kode = 'MU80-8KG';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'MUS-SP';
update items set kategori = 'SARANA PERTANIAN' where kode = 'MV-17KG';
update items set kategori = 'BAYER' where kode = 'MVTE-50ML';
update items set kategori = 'BAYER' where kode = 'MVTEN-100ML';
update items set kategori = 'MEROKE' where kode = 'MZN-500GR';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'NAU-RG';
update items set kategori = 'BIBIT JAGUNG MANIS PANAH MERAH' where kode = 'NBS-SP';
update items set kategori = null where kode = 'NF-160SL';
update items set kategori = null where kode = 'NF1-160SL';
update items set kategori = null where kode = 'NF2-160SL';
update items set kategori = null where kode = 'NG-100ML';
update items set kategori = null where kode = 'NG-50ML';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'NIT-25GR';
update items set kategori = 'PUPUK' where kode = 'NK9.34-50KG';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'NMET-800S';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'NMET-SP';
update items set kategori = 'FUNGISIDA' where kode = 'NOR-100GR';
update items set kategori = 'FUNGISIDA' where kode = 'NOR-500GR';
update items set kategori = 'AIC/JAI' where kode = 'NOS-250ML';
update items set kategori = 'AIC/JAI' where kode = 'NOS-500ML';
update items set kategori = null where kode = 'NP-100ML';
update items set kategori = null where kode = 'NP-500ML';
update items set kategori = 'SAPROTAN UTAMA' where kode = 'NPK 7-6-35 - 50KG';
update items set kategori = 'SAPROTAN UTAMA' where kode = 'NPK-12.12.17+2 50KG';
update items set kategori = 'SAPROTAN UTAMA' where kode = 'NPK-15.15.6.4 50KG';
update items set kategori = 'DGW' where kode = 'NPK12-1KG';
update items set kategori = 'SAPROTAN UTAMA' where kode = 'NPK13.6.27-50KG';
update items set kategori = 'SAPROTAN UTAMA' where kode = 'NPK15-50KG';
update items set kategori = 'SAPROTAN UTAMA' where kode = 'NPK16-1KG';
update items set kategori = 'SAPROTAN UTAMA' where kode = 'NPK16-50KG';
update items set kategori = 'SAPROTAN UTAMA' where kode = 'NPKC16-50KG';
update items set kategori = 'DGW' where kode = 'NPKCOM-5KG';
update items set kategori = 'PETROKIMIA' where kode = 'NPSN-50KG';
update items set kategori = 'SANTANI' where kode = 'NS20-50KG';
update items set kategori = 'PUPUK' where kode = 'NTJ-5KG';
update items set kategori = 'BAYER' where kode = 'NTV-12,5GR';
update items set kategori = 'PANCA AGRO NIAGA' where kode = 'NTV-50GR';
update items set kategori = 'NUFARM' where kode = 'OBV-100ML';
update items set kategori = 'EXCEL MEG INDO' where kode = 'ONE-100ML';
update items set kategori = 'EXCEL MEG INDO' where kode = 'ONE-SH 250ML';
update items set kategori = 'SYNGENTA' where kode = 'ORO-500ML';
update items set kategori = 'PUPUK' where kode = 'PAC-20KG';
update items set kategori = 'PANEN RAYA' where kode = 'PAN-100X17KG';
update items set kategori = 'PANEN RAYA' where kode = 'PAN-12017KG';
update items set kategori = 'PANEN RAYA' where kode = 'PAN-120X8KG';
update items set kategori = 'BIBIT JAGUNG MANIS PERTIWI' where kode = 'PAR-1750S';
update items set kategori = 'PT ADIL MAKMUR' where kode = 'PAR-1LTR';
update items set kategori = 'PT ADIL MAKMUR' where kode = 'PAR-20LTR';
update items set kategori = 'PT ADIL MAKMUR' where kode = 'PAR-4LTR';
update items set kategori = 'PT ADIL MAKMUR' where kode = 'PAR-500ML';
update items set kategori = 'PT ADIL MAKMUR' where kode = 'PAR-5LTR';
update items set kategori = null where kode = 'PC-100ML';
update items set kategori = 'NUFARM' where kode = 'PCB-800GR';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'PEL-SP';
update items set kategori = 'SARANA PERTANIAN' where kode = 'PEN - MUL';
update items set kategori = 'SOLO LOGO' where kode = 'PEN-1LTR';
update items set kategori = 'SANTANI' where kode = 'PER15.5.20-1KG';
update items set kategori = 'BIBIT JAGUNG MANIS PERTIWI' where kode = 'PER3-1KG';
update items set kategori = 'PETROKIMIA' where kode = 'PET-100GR';
update items set kategori = 'RODENTISIDA' where kode = 'PET-1KG';
update items set kategori = 'PETROKIMIA' where kode = 'PGN-5ML';
update items set kategori = 'SANTANI' where kode = 'PGT-100ML';
update items set kategori = 'SANTANI' where kode = 'PGT-250ML';
update items set kategori = 'SANTANI' where kode = 'PGT-500ML';
update items set kategori = 'SAPROTAN UTAMA' where kode = 'PHG-50KG';
update items set kategori = 'CBA' where kode = 'PIL-5GR';
update items set kategori = 'PESTISIDA' where kode = 'PKTKRT-100ML';
update items set kategori = 'SYNGENTA' where kode = 'PLE-25GR';
update items set kategori = 'DGW' where kode = 'PMS-50KG';
update items set kategori = 'SAPROTAN UTAMA' where kode = 'PNP-1KG';
update items set kategori = 'DGW' where kode = 'PNP-50KG';
update items set kategori = null where kode = 'PNT-5GR';
update items set kategori = 'SAPROTAN UTAMA' where kode = 'POS-250ML';
update items set kategori = 'SAPROTAN UTAMA' where kode = 'POS-80ML';
update items set kategori = 'AIC/JAI' where kode = 'POU-200ML';
update items set kategori = 'AIC/JAI' where kode = 'POU-400ML';
update items set kategori = 'DGW' where kode = 'POW-16L';
update items set kategori = 'FMC' where kode = 'PRE-100ML';
update items set kategori = 'FMC' where kode = 'PRE-250ML';
update items set kategori = 'MEROKE' where kode = 'PRM-500GR';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'PRO-SP';
update items set kategori = 'NUFARM' where kode = 'PRT-400ML';
update items set kategori = 'MITRA MERDEKA TANI' where kode = 'PWS-1KG';
update items set kategori = 'MITRA MERDEKA TANI' where kode = 'PWS-500GR';
update items set kategori = 'SAPROTAN UTAMA' where kode = 'QTX-1LTR';
update items set kategori = 'SAPROTAN UTAMA' where kode = 'QTX-20LTR';
update items set kategori = 'SAPROTAN UTAMA' where kode = 'QTX-4LTR';
update items set kategori = 'SANTANI' where kode = 'RAC-100GR';
update items set kategori = 'SANTANI' where kode = 'RAC-1KG';
update items set kategori = 'SANTANI' where kode = 'RAC-4KG';
update items set kategori = 'SGI' where kode = 'RAL-1LT';
update items set kategori = 'SGI' where kode = 'RAL-20LTR';
update items set kategori = 'SGI' where kode = 'RAL-4LT';
update items set kategori = 'SGI' where kode = 'RAL-500ML';
update items set kategori = 'DGW' where kode = 'RAP-500GR';
update items set kategori = 'BIOTIS' where kode = 'RAP-5GR';
update items set kategori = 'AGRICON' where kode = 'RAT-1KG';
update items set kategori = 'AGRICON' where kode = 'RAT-5KG';
update items set kategori = 'PUPUK' where kode = 'RBK-16';
update items set kategori = 'SYNGENTA' where kode = 'RDG-100GR';
update items set kategori = 'SYNGENTA' where kode = 'RDG-250GR';
update items set kategori = 'SYNGENTA' where kode = 'RDG-500GR';
update items set kategori = 'SGI' where kode = 'RDM-1LTR';
update items set kategori = 'SGI' where kode = 'RDM-200ML';
update items set kategori = 'SGI' where kode = 'RDM-400ML';
update items set kategori = 'SGI' where kode = 'REA-1LTR';
update items set kategori = 'SGI' where kode = 'REA-20LTR';
update items set kategori = 'SGI' where kode = 'REA-4LT';
update items set kategori = 'SGI' where kode = 'REA-500ML';
update items set kategori = 'BASF' where kode = 'REGR-100ML';
update items set kategori = 'BASF' where kode = 'REGR-250ML';
update items set kategori = 'BASF' where kode = 'REGR-50ML';
update items set kategori = 'BASF' where kode = 'RG3-1KG';
update items set kategori = 'BUNGA TANI' where kode = 'RJB-2.5KG';
update items set kategori = 'NUFARM' where kode = 'ROU-1LTR';
update items set kategori = 'NUFARM' where kode = 'ROU-200ML';
update items set kategori = 'NUFARM' where kode = 'ROU-20LTR';
update items set kategori = 'NUFARM' where kode = 'ROU-4LTR';
update items set kategori = 'PETROKIMIA' where kode = 'RPM-50KG';
update items set kategori = null where kode = 'RPP-DS50KG';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'RUM-10GR';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'RUM-SP';
update items set kategori = 'SANTANI' where kode = 'SAL-250ML';
update items set kategori = 'SANTANI' where kode = 'SAL-500ML';
update items set kategori = 'SANTANI' where kode = 'SAN-100GR';
update items set kategori = 'SANTANI' where kode = 'SAN-1LT';
update items set kategori = 'SANTANI' where kode = 'SAN-250ML';
update items set kategori = 'SANTANI' where kode = 'SAN-400GR';
update items set kategori = 'SANTANI' where kode = 'SAN-5LT';
update items set kategori = 'FUNGISIDA' where kode = 'SAR-5GR';
update items set kategori = 'BELL' where kode = 'SB10-100';
update items set kategori = 'BELL' where kode = 'SB15-100';
update items set kategori = 'BELL' where kode = 'SB4-100';
update items set kategori = 'BELL' where kode = 'SB4-250';
update items set kategori = 'BELL' where kode = 'SB6-100';
update items set kategori = 'BELL' where kode = 'SB7-100';
update items set kategori = 'PANEN RAYA' where kode = 'SBG04-200MT';
update items set kategori = 'BIBIT' where kode = 'SBP-20GR';
update items set kategori = 'PUPUK' where kode = 'SBR-5KG';
update items set kategori = 'BIBIT' where kode = 'SBW-20GR';
update items set kategori = 'SYNGENTA' where kode = 'SCR-250ML';
update items set kategori = 'SYNGENTA' where kode = 'SCR-80ML';
update items set kategori = 'LAIN-LAIN' where kode = 'SDA-25KG';
update items set kategori = 'PETROSIDA' where kode = 'SDM-100ML';
update items set kategori = 'PETROSIDA' where kode = 'SDM-400ML';
update items set kategori = 'BIBIT JAGUNG MANIS PANAH MERAH' where kode = 'SEC88-1750S';
update items set kategori = 'BIBIT JAGUNG MANIS PANAH MERAH' where kode = 'SEC88-SP';
update items set kategori = 'DGW' where kode = 'SEE-16LTR';
update items set kategori = 'PANEN RAYA' where kode = 'SEL-12.5X200MT';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'SER-1750S';
update items set kategori = 'NUFARM' where kode = 'SER-25GR';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'SER-SP';
update items set kategori = 'AGRICON' where kode = 'SEV-100GR';
update items set kategori = 'AGRICON' where kode = 'SEV-500GR';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'SHI-25GR';
update items set kategori = 'PETROSIDA' where kode = 'SID-100ML';
update items set kategori = 'NUFARM' where kode = 'SIK-25GR';
update items set kategori = 'LAIN-LAIN' where kode = 'SIN-1LTR';
update items set kategori = 'LAIN-LAIN' where kode = 'SIN-250ML';
update items set kategori = 'BIBIT' where kode = 'SK-25GR';
update items set kategori = 'SANTANI' where kode = 'SL-100ML';
update items set kategori = 'SANTANI' where kode = 'SL-250ML';
update items set kategori = 'PLASINDO' where kode = 'SLI-16LTR';
update items set kategori = 'PUPUK' where kode = 'SLM-50KG';
update items set kategori = 'SANTANI' where kode = 'SM-1KG';
update items set kategori = 'PLASINDO' where kode = 'SMB-2IN1';
update items set kategori = 'SYNGENTA' where kode = 'SMD-100ML';
update items set kategori = 'INSEKTISIDA' where kode = 'SMT-100ML';
update items set kategori = 'SANTANI' where kode = 'SMZ-1KG';
update items set kategori = 'NOKAKU' where kode = 'SN1-16LTR';
update items set kategori = 'NOKAKU' where kode = 'SN2-16LTR';
update items set kategori = 'SANTANI' where kode = 'SNA-200GR';
update items set kategori = null where kode = 'SNF-5GR';
update items set kategori = 'NOKAKU' where kode = 'SNP-2LTR';
update items set kategori = 'SARANA PERTANIAN' where kode = 'SNS-330';
update items set kategori = 'LAIN-LAIN' where kode = 'SOD-50KG';
update items set kategori = 'AIC/JAI' where kode = 'SPA-1L';
update items set kategori = 'AIC/JAI' where kode = 'SPA-250ML';
update items set kategori = 'AIC/JAI' where kode = 'SPA-500ML';
update items set kategori = 'PLASINDO' where kode = 'SPB-16L';
update items set kategori = 'DGW' where kode = 'SPD-250ML';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'SPD-SP';
update items set kategori = null where kode = 'SPDK';
update items set kategori = 'DGW' where kode = 'SPE-16LTR';
update items set kategori = 'PETROKIMIA' where kode = 'SPE-50KG';
update items set kategori = 'PUPUK CAIR ORGANIK' where kode = 'SPM-1LTR';
update items set kategori = 'PUPUK CAIR ORGANIK' where kode = 'SPM-300ML';
update items set kategori = 'PUPUK' where kode = 'SPN-20KG';
update items set kategori = 'PETROKIMIA' where kode = 'SPN36-50KG';
update items set kategori = 'AGRICON' where kode = 'SPON-1LTR';
update items set kategori = 'AGRICON' where kode = 'SPON-200ML';
update items set kategori = 'AGRICON' where kode = 'SPON-500ML';
update items set kategori = 'PLASINDO' where kode = 'SPP-10L';
update items set kategori = 'PLASINDO' where kode = 'SPP-7L';
update items set kategori = 'PLASINDO' where kode = 'SPP-8L';
update items set kategori = 'MEROKE' where kode = 'SPR-1KG';
update items set kategori = 'DGW' where kode = 'SPR-500ML';
update items set kategori = 'MEROKE' where kode = 'SPR-50KG';
update items set kategori = 'DGW' where kode = 'SPT-1LTR';
update items set kategori = 'DGW' where kode = 'SPT-20LTR';
update items set kategori = 'DGW' where kode = 'SPT-4LTR';
update items set kategori = 'PETROKIMIA' where kode = 'SPT-50KG';
update items set kategori = 'NUFARM' where kode = 'SRL-500ML';
update items set kategori = 'MEROKE' where kode = 'SSA-50KG';
update items set kategori = 'PLASINDO' where kode = 'SSP-16LTR';
update items set kategori = null where kode = 'ST-C1KG';
update items set kategori = null where kode = 'ST-C25KG';
update items set kategori = 'NUFARM' where kode = 'STA-100ML';
update items set kategori = 'NUFARM' where kode = 'STA-1LTR';
update items set kategori = 'CORTEVA' where kode = 'STA-500ML';
update items set kategori = 'BIOTIS' where kode = 'STB-400ML';
update items set kategori = 'BIOTIS' where kode = 'STD-200ML';
update items set kategori = 'SANTANI' where kode = 'STG-50KG';
update items set kategori = 'TANIKU' where kode = 'STH-2LTR';
update items set kategori = 'AGRICON' where kode = 'STK-1LTR';
update items set kategori = 'AGRICON' where kode = 'STK-500ML';
update items set kategori = 'SANTANI' where kode = 'STO-100ML';
update items set kategori = 'SANTANI' where kode = 'STO-1LTR';
update items set kategori = 'SANTANI' where kode = 'STQ-20LTR';
update items set kategori = 'SANTANI' where kode = 'STQ-4LTR';
update items set kategori = 'PT ADIL MAKMUR' where kode = 'SUN-1LTR';
update items set kategori = 'PT ADIL MAKMUR' where kode = 'SUN-20LTR';
update items set kategori = 'PT ADIL MAKMUR' where kode = 'SUN-4LTR';
update items set kategori = 'DGW' where kode = 'SUP-1LTR';
update items set kategori = 'DGW' where kode = 'SUP-20LTR';
update items set kategori = 'DGW' where kode = 'SUP-4LTR';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'SUP-95S';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'SUP-SP';
update items set kategori = 'SAPROTAN UTAMA' where kode = 'SUT 560SC- 500ML';
update items set kategori = 'BIOTIS' where kode = 'TAN-100ML';
update items set kategori = 'BIOTIS' where kode = 'TAN-250ML';
update items set kategori = 'BIOTIS' where kode = 'TAN-50ML';
update items set kategori = 'BELL' where kode = 'TBELL-0,6 ONS';
update items set kategori = 'BELL' where kode = 'TBH-0.3ONS';
update items set kategori = 'JIMMY HANTU' where kode = 'THH-1LTR';
update items set kategori = 'JIMMY HANTU' where kode = 'THH-500ML';
update items set kategori = 'SGI' where kode = 'TIM-1LT';
update items set kategori = 'SGI' where kode = 'TIM-20LT';
update items set kategori = 'SGI' where kode = 'TIM-4LT';
update items set kategori = 'PUPUK' where kode = 'TKDO-50KG';
update items set kategori = 'SAPROTAN UTAMA' where kode = 'TOR-200ML';
update items set kategori = 'SAPROTAN UTAMA' where kode = 'TOR-80ML';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'TOS-25GR';
update items set kategori = 'PETROKIMIA' where kode = 'TPB-100GR';
update items set kategori = 'PETROKIMIA' where kode = 'TPB-500GR';
update items set kategori = 'PETROSIDA' where kode = 'TPR-100GR';
update items set kategori = 'PETROSIDA' where kode = 'TPR-400GR';
update items set kategori = 'BELL' where kode = 'TRAY-105';
update items set kategori = 'BELL' where kode = 'TRAY-128';
update items set kategori = 'BELL' where kode = 'TRAY-200';
update items set kategori = 'BELL' where kode = 'TRAY-288';
update items set kategori = 'BELL' where kode = 'TRAY-72';
update items set kategori = 'DGW' where kode = 'TRD-250GR';
update items set kategori = 'DGW' where kode = 'TRD-5GR';
update items set kategori = 'SAPROTAN UTAMA' where kode = 'TRM-100GR';
update items set kategori = 'MULTI SARANA INDOTANI' where kode = 'TRSL-100ML';
update items set kategori = 'MULTI SARANA INDOTANI' where kode = 'TRSL-500ML';
update items set kategori = 'SOLO LOGO' where kode = 'TUN-1LTR';
update items set kategori = 'SOLO LOGO' where kode = 'TUN-4LTR';
update items set kategori = 'SAPROTAN UTAMA' where kode = 'ULT-20GR';
update items set kategori = 'SAPROTAN UTAMA' where kode = 'ULT-8GR';
update items set kategori = 'PUPUK' where kode = 'UNG-50KG';
update items set kategori = 'SAPROTAN UTAMA' where kode = 'URC-50KG';
update items set kategori = 'SANTANI' where kode = 'URE-50KG';
update items set kategori = 'SANTANI' where kode = 'UREN-25KG';
update items set kategori = 'BUNGA TANI' where kode = 'URS-1LTR';
update items set kategori = 'SAPROTAN UTAMA' where kode = 'UTD-1KG';
update items set kategori = 'AGRICON' where kode = 'UTX-100ML';
update items set kategori = 'BELL' where kode = 'UVB-200X50M';
update items set kategori = 'AIC/JAI' where kode = 'VEC-1LTR';
update items set kategori = 'AIC/JAI' where kode = 'VEC-20LTR';
update items set kategori = 'AIC/JAI' where kode = 'VEC-4LTR';
update items set kategori = 'VITAMIN KARET' where kode = 'VIK-250ML';
update items set kategori = 'INSEKTISIDA' where kode = 'VIP-100ML';
update items set kategori = 'INSEKTISIDA' where kode = 'VIP-200ML';
update items set kategori = 'SYNGENTA' where kode = 'VIR-100ML';
update items set kategori = 'SYNGENTA' where kode = 'VIR-50ML';
update items set kategori = 'SAPROTAN UTAMA' where kode = 'VIT-500ML';
update items set kategori = 'MITRA MERDEKA TANI' where kode = 'VITA-1LTR';
update items set kategori = 'MITRA MERDEKA TANI' where kode = 'VITA-500ML';
update items set kategori = 'DGW' where kode = 'VNTR-500ML';
update items set kategori = 'SGI' where kode = 'VPR-100ML';
update items set kategori = 'SGI' where kode = 'VPR-250ML';
update items set kategori = 'SGI' where kode = 'VPR-50ML';
update items set kategori = 'BAYER' where kode = 'VYG-100ML';
update items set kategori = 'BAYER' where kode = 'VYGN-50ML';
update items set kategori = 'AIC/JAI' where kode = 'WIN-1LTR';
update items set kategori = 'AIC/JAI' where kode = 'WIN-20LTR';
update items set kategori = 'AGRICON' where kode = 'WIN-250GR';
update items set kategori = 'AIC/JAI' where kode = 'WRT-1LTR';
update items set kategori = 'AIC/JAI' where kode = 'WRT-20LTR';
update items set kategori = 'AIC/JAI' where kode = 'WRT-4LTR';
update items set kategori = 'NUFARM' where kode = 'WUZ-100ML';
update items set kategori = 'NUFARM' where kode = 'WZN-250ML';
update items set kategori = 'PUPUK' where kode = 'YMA-50KG';
update items set kategori = 'PETROKIMIA' where kode = 'YNT-100GR';
update items set kategori = 'PETROKIMIA' where kode = 'YNT-15GR';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'YUM-1100S';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'YUV-1100S';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'YUV-SP';
update items set kategori = 'MEROKE' where kode = 'ZAH-50KG';
update items set kategori = 'BIBIT SAYURAN PANAH MERAH' where kode = 'ZAT-SP';
update items set kategori = 'NUFARM' where kode = 'ZEN-1KG';
update items set kategori = 'BIOTIS' where kode = 'ZEN-4LTR';
update items set kategori = 'SGI' where kode = 'ZIP-15GR';
update items set kategori = 'SGI' where kode = 'ZPH-100GR';
